### ISSUE TITLE
Priority order in run method

### ISSUE THREAD

**Issue by BFalquet** [insightsengineering/chevron#693]
When arguments are passed to the `run` method using both `...` and `user_args`, only `user_args` is taken into account. This causes surprising behavior for the user who has the impression that they can't control the function.

**Comment by clarkliming** [comment]
related to run method: is it possible that `chevron_tlg` inherits `function`, and make its .Data the run method?

in that case we can even use

`aet01(aa,bb,cc)` instead of `run(aet01, aa, bb,cc)` ?

**Comment by BFalquet** [comment]
We could but it is a very serious refactoring, I am not sure the users would appreciate.

**Comment by clarkliming** [comment]
> We could but it is a very serious refactoring, I am not sure the users would appreciate (in the first version of chevron, it was like that)

it is not a very serious refactoring, we can easily make S4 callable; but still this is some wild thoughts and ideas.

prototypes


```
.chevron_tlg <- setClass(
  "chevron_tlg",
  contains = c("VIRTUAL", "function"),
  slots = c(
    main = "function",
    preprocess = "function",
    postprocess = "function"
  ),
  prototype =  function(...) {run(sys.function(), ...)}
)
```

still, the `run` method is called.

```
run(aet02, ...)
aet02(...)
```
should work identically
