### ISSUE TITLE
properly document non-function object

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/chevron#714]
currently chevron_tlg objects are documented as objects, and the corresponding pre,main functions are documented in the same Rd file.

CRAN requires for function `value` should be included in documentation, but for objects it do not have that slot.

`survival::survreg.distributions` and `emmeans::emm_defaults` do not have value in docs, but our case is a bit more complicated as other functions are also inside this doc.

any idea of how we should properly document these objects?

**Comment by clarkliming** [comment]
PS: a simple function to find the non-function and non-data frame objs. just no good place to store this code

```
find_non_function_obj <- function(x) {
  library(package = x, character.only = TRUE)
  nmsp <- sprintf("package:%s", x)
  objs <- ls(pos = nmsp)
  objs <- setNames(objs, objs)
  obj <- lapply(objs, function(s) {get(s, nmsp)})
  non_fun <- Filter(function(s) {!is.function(s) && !is.data.frame(s)}, obj)
  non_fun
}
find_non_function_obj("emmeans")
```

**Comment by BFalquet** [comment]
I think we are ok: https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-other.html

**Comment by BFalquet** [comment]
The package has been accepted on CRAN and doesn't require anymore a change in the way objects are documented.
